export const SET_SKIN ="SET_SKIN";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER = "REGISTER";
export const SIGN_IN ="SIGN_IN";
export const SIGN_IN_FAILED ="SIGN_IN_FAILED";

export const UPDATE_CONTACT="UPDATE_CONTACT"
export const UPDATE_CONTACT_ERROR="UPDATE_CONTACT_ERROR"
export const UPDATE_SKIN="UPDATE_SKIN"
export const UPDATE_SKIN_ERROR="UPDATE_SKIN_ERROR"
export const ADD_CONTACT="ADD_CONTACT"
export const ADD_CONTACT_ERROR="ADD_CONTACT_ERROR"


export const ADD_EDUCATION="ADD_EDUCATION"
export const ADD_EDUCATION_ERROR="ADD_EDUCATION_ERROR"
export const UPDATE_EDUCATION="UPDATE_EDUCATION"
export const UPDATE_EDUCATION_ERROR="UPDATE_EDUCATION_ERROR"

export const SIGN_OUT ="SIGN_OUT";


export const REMOVE_TASK ="REMOVE_TASK";
export const REMOVE_TASK_ERR = "REMOVE_TASK_ERR";


export const UPDATE_BGCOLOR ="UPDATE_BGCOLOR";
export const UPDATE_BGCOLOR_ERROR = "UPDATE_BGCOLOR_ERROR";

export const UPDATE_FONTFAMILY ="UPDATE_FONTFAMILY";
export const UPDATE_FONTFAMILY_ERROR = "UPDATE_FONTFAMILY_ERROR";

export const UPDATE_FONTSIZE ="UPDATE_FONTSIZE";
export const UPDATE_FONTSIZE_ERROR = "UPDATE_FONTSIZE_ERROR";